### ISSUE TITLE
Add cursor styles

### ISSUE THREAD

**Issue by trumbitta** [trumbitta/bootstrap-css-utils#1]
Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

Example: 

``` css
.cursor-pointer: {
  cursor: pointer;
}
```
